### ISSUE TITLE
bee keeper crash

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Faboslav/friends-and-foes#15]
### Minecraft version information

1.18.1

### Mod version information

1.2.2

### Reproduction Steps

i dont know i think my game crash becouse a old villager took the bee job a villarger that was around before installing this mod not sure

### Crash Report and latest.log

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 30-01-2022 17:30
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2758{name=honey_level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.isBeehiveReadyForHarvest(BeekeeperWorkTask.java:79)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_26335(BeekeeperWorkTask.java:53)
	at net.minecraft.class_4133.method_21642(class_4133.java:56)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_21642(BeekeeperWorkTask.java:28)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_18920(BeekeeperWorkTask.java:21)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4103$class_4216$1.method_19561(class_4103.java:97)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at net.minecraft.class_4103$class_4216$1.method_19559(class_4103.java:98)
	at net.minecraft.class_4103.method_18920(class_4103.java:54)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:511)
	at net.minecraft.class_4095.method_19542(class_4095.java:470)
	at net.minecraft.class_1646.method_5958(class_1646.java:273)
	at net.minecraft.class_1308.method_6023(class_1308.java:758)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_1646.method_5773(class_1646.java:314)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.isBeehiveReadyForHarvest(BeekeeperWorkTask.java:79)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_26335(BeekeeperWorkTask.java:53)
	at net.minecraft.class_4133.method_21642(class_4133.java:56)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_21642(BeekeeperWorkTask.java:28)
	at com.faboslav.friendsandfoes.entity.passive.ai.brain.task.BeekeeperWorkTask.method_18920(BeekeeperWorkTask.java:21)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4103$class_4216$1.method_19561(class_4103.java:97)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at net.minecraft.class_4103$class_4216$1.method_19559(class_4103.java:98)
	at net.minecraft.class_4103.method_18920(class_4103.java:54)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:511)
	at net.minecraft.class_4095.method_19542(class_4095.java:470)
	at net.minecraft.class_1646.method_5958(class_1646.java:273)
	at net.minecraft.class_1308.method_6023(class_1308.java:758)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_1646.method_5773(class_1646.java:314)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 720
	Entity Name: Beekeeper
	Entity's Exact location: 234.55, 67.00, 61.57
	Entity's Block location: World: (234,67,61), Section: (at 10,3,13 in 14,4,3; chunk contains blocks 224,-64,48 to 239,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['ShadowSlayerFX1'/590, l='ServerLevel[ShadowLands]', x=215.18, y=73.00, z=140.44]]
	Chunk stats: 2642
	Level dimension: minecraft:overworld
	Level spawn location: World: (40,91,-6), Section: (at 8,11,10 in 2,5,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 871262 game time, 294810 day time
	Level name: ShadowLands
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 7572 (now: false), thunder time: 53625 (now: false)
	Known server brands: forge, fabric, vanilla
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3039876176 bytes (2899 MiB) / 6677331968 bytes (6368 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3,19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072,00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25558,48
	Virtual memory used (MB): 14853,86
	Swap memory total (MB): 9216,00
	Swap memory used (MB): 214,48
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adventurez: AdventureZ 1.4.7
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		arcanus: Arcanus 1.27
		archeology: CapsLock Archeology Mod 0.1.8
		architectury: Architectury 3.5.12
		awesomedungeon: Awesome Dungeon 2.0.4
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.0
		backslot: BackSlot 1.2.4
		backslotaddon: BackSlot Addon 1.0.7
		bclib: BCLib 1.2.4
		betterend: Better End 1.0.0
		betternether: Better Nether 6.0.8
		biom4st3r_libs_biow0rks_reflection: reflection 0.1.2
		biomemakeover: Biome Makeover 1.18.1-1.4.3
		biow0rks-base: biow0rks-base 0.1.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		byg: BYG 1.3.5.6
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		cenchants: Combat Enchants 1.12.0
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.1.50
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		coat: Coat 1.0.0-beta.15
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 1.0.0-1.18
		compactstatuseffects: Compact Status Effects 2.1.1
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		crawl: Crawl 0.10.2
		dehydration: Dehydration 1.2.7
		disenchanter: Disenchanter 0.1.4+1.18
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.10
		dualwielding: Dual Wielding 1.0.7
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		dynamicfps: Dynamic FPS 2.1.0
		edenring: EdenRing 0.2.1
		enchant_giver: Enchant Giver 1.1.0
		enderitemod: Enderite Mod 1.3.3
		endgoblintraders: End Goblin Traders 1.4.2
		environmentz: EnvironmentZ 1.2.1
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.11+e66b59e93a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricenchantments: Fabric Enchantments 0.7.0
		fabricloader: Fabric Loader 0.12.12
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.2.2
		geckolib3: Geckolib 3.0.27
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.61
		goblintraders: Goblin Traders 1.4.1
		hookshot: Hookshot 23.0
		infusion_table: Infusion Table 1.0.5
		inventoryhud: Inventory HUD + 3.4.2
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.1-1.18
		kibe: Kibe 1.9.4-BETA+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		libraryferret: Library Ferret 1.0.3
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magiccombatwands: Magic Combat Wands 1.0.1
		mcda: MC Dungeons Armors 1.9.0
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 4.0.3
		mdi: More Dumb Items 4.1.1
		medievalweapons: Medieval Weapons 1.1.7
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		moenchantments: Mo'Enchantments 2.0.0
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		omega-config: OmegaConfig 1.2.2-1.18.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		patchouli: Patchouli 1.18.1-64-FABRIC
		phosphor: Phosphor 0.8.1
		playerabilitylib: Pal 1.4.0
		pride: Pride Lib 1.1.0+1.17
		pugh_lib: Pugh Lib 1.2.15
		pugh_tools: Pugh Tools 1.1.17
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 3.3.6+1.18.1
		rotten: FleshZ 1.4.4
		sculk_worm: Sculk Worm 0.1.3
		seedfix: Seed Fix 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.9
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spellbound: Spellbound 1.7.2
		spruceui: SpruceUI 3.3.0+1.17
		stoneholm: Stoneholm 1.4.1
		terrablender: TerraBlender 1.1.0.71
		terralith: Terralith for Fabric 2.0.12
		thonkutil: ThonkUtil 1.3
		trapexpansion: Trap Expansion 1.3.3
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		twm: The Wild Mod 0.5
		urns: Urns 1.0.1
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.1.1+mc1.18.1
		waystones: Waystones 2.4.1
		xaerominimap: Xaero's Minimap 21.23.1
		xaeroworldmap: Xaero's World Map 1.19.1
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['ShadowSlayerFX1'/590, l='ServerLevel[ShadowLands]', x=215.18, y=73.00, z=140.44]]
	Data Packs: vanilla, file/BlazeandCaves Advancements Pack 1.13.2, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

### Additional information

my game crash in the crash report says something about the bee keeper

**Comment by Faboslav** [comment]
I found the issue, even I dont get it, why minecraft does run the beekeepers work task when his point of interest (beehive block) does not exists.

Is it okay, that i will release this fix next weekend? As of today I already released a minor version and i would like to wait for other issues or improvements(if any) for this specific reason for next weekend.

**Comment by Faboslav** [comment]
So new version is available, let me please know if the issue is resolved:
https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.18.1-1.2.3
https://www.curseforge.com/minecraft/mc-mods/friends-and-foes/files/3637344
