### ISSUE TITLE
Fails to load using Quilt version, but loads using Fabric version

### ISSUE THREAD

**Issue by amyfromearth** [Faboslav/friends-and-foes#152]
### Minecraft version information

1.20.1

### Mod loader information

Quilt

### Mod loader version information

0.21.0

### Mod version information

Friends&Foes mc1.20.1-1.9.3 (Quilt)

### Reproduction Steps

Installing Quilt Version of Friends & Foes into my modpack and it failed to load. Installed Fabric version and it works as expected. 

### Crash Report and latest.log

[crash-2023-10-15_17.18.51.0169-quilt_loader.txt](https://github.com/Faboslav/friends-and-foes/files/12911052/crash-2023-10-15_17.18.51.0169-quilt_loader.txt)

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#friendsandfoes:friendsandfoes-common.mixins.json:PlayerEntityMixin from mod friendsandfoes] from phase [DEFAULT] in config [#friendsandfoes:friendsandfoes-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on friendsandfoes_addToTick could not find any targets matching 'tick' in net.minecraft.class_1657. No refMap loaded. [PREINJECT Applicator Phase -> #friendsandfoes:friendsandfoes-common.mixins.json:PlayerEntityMixin from mod friendsandfoes -> Prepare Injections ->  -> handler$eke000$friendsandfoes$addToTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by Faboslav** [comment]
Quilt is not directly supported anymore(and will not be until stable release), please do use fabric.
