### ISSUE TITLE
spam in log something is null

### ISSUE THREAD

**Issue by monkeybee11** [Faboslav/friends-and-foes#169]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.24-1.20.1

### Mod version information

2.0.2 

### Expected Behavior

no spam in consoual

### Actual Behavior

this is being spamed in my consoul logs.... ALOOOOOOOOOOOT!!!!!11!!!! :P 

`Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.faboslav.friendsandfoes.api.MoobloomVariant.getName()" because the return value of "com.faboslav.friendsandfoes.api.MoobloomVariantManager.getDefaultMoobloomVariant()" is null
	at com.faboslav.friendsandfoes.entity.MoobloomEntity.method_5693(MoobloomEntity.java:89)
	at net.minecraft.class_1297.<init>(class_1297.java:297)
	at net.minecraft.class_1309.<init>(class_1309.java:246)
	at net.minecraft.class_1308.<init>(class_1308.java:133)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:29)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at net.minecraft.class_1430.<init>(class_1430.java:37)
	at com.faboslav.friendsandfoes.entity.MoobloomEntity.<init>(MoobloomEntity.java:50)
	at net.minecraft.class_1299.method_5883(class_1299.java:544)
	at net.minecraft.class_634.method_11112(class_634.java:472)
	at net.minecraft.class_2604.method_11178(class_2604.java:99)
	at net.minecraft.class_2604.method_11054(class_2604.java:15)
	at net.minecraft.class_634.method_48294(class_634.java:2485)
	at net.minecraft.class_8042.method_48329(class_8042.java:13)
	at net.minecraft.class_8042.method_11054(class_8042.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

### Reproduction Steps

think its happening when ever a moobloom enters loaded chunks ive got some wild ones just outside of rendered chunks of my house

**Comment by Faboslav** [comment]
Can i get the full log please, with loaded mods and everything?

**Comment by monkeybee11** [comment]
[latest.log](https://github.com/Faboslav/friends-and-foes/files/13621349/latest.log)
this one????

**Comment by Faboslav** [comment]
This is related to https://github.com/Faboslav/friends-and-foes/issues/169, will try to fix it as soon as possible.

**Comment by Faboslav** [comment]
This should be fixed with the 2.0.3 version of the mod.
