### ISSUE TITLE
crash when i attempt to load blockus (https://www.curseforge.com/minecraft/mc-mods/blockus) via sinytra connector; friends and foes is implicated in the crash report

### ISSUE THREAD

**Issue by veccyboi** [Faboslav/friends-and-foes#277]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

forge 47.2.30

### Mod version information

3.0.3

### Reproduction Steps

i first noticed this issue yesterday and reported it to the blockus devs here: https://github.com/Brandcraf06/Blockus/issues/341
however, I did some more digging in the crash report this morning and noticed this stacktrace: `Caused by: java.lang.NullPointerException: Registry Object not present: friendsandfoes:copper_button
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.2.30-universal.jar%231019!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_registry_lambda.RegistryObjectMixin from mod modernfix,pl:mixin:A}
	at com.faboslav.friendsandfoes.common.init.registry.forge.ForgeRegistryEntry.get(ForgeRegistryEntry.java:25) ~[friendsandfoes-forge-mc1.20.1-3.0.3.jar%23765!/:?] {re:classloading}
	at com.faboslav.friendsandfoes.common.util.WaxableBlocksMap.lambda$static$1(WaxableBlocksMap.java:28) ~[friendsandfoes-forge-mc1.20.1-3.0.3.jar%23765!/:?] {re:mixin,re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.minecraft.world.item.HoneycombItem.modifyReceiver$dji000$friendsandfoes$inject(HoneycombItem.java:1016) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-content-registries-v0.mixins.json:HoneycombItemMixin from mod fabric_content_registries_v0,pl:mixin:APP:friendsandfoes-common.mixins.json:HoneycombItemMixin from mod friendsandfoes,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.item.HoneycombItem.m_150881_(HoneycombItem.java:42) ~[client-1.20.1-20230612.114412-srg.jar%231014!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-content-registries-v0.mixins.json:HoneycombItemMixin from mod fabric_content_registries_v0,pl:mixin:APP:friendsandfoes-common.mixins.json:HoneycombItemMixin from mod friendsandfoes,pl:mixin:A,pl:connector_pre_launch:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.fabricmc.fabric.api.registry.OxidizableBlocksRegistry.registerWaxableBlockPair(OxidizableBlocksRegistry.java:53) ~[fabric-content-registries-v0-4.0.11+a670df1e77.jar%231189!/:4.0.11+a670df1e77] {re:classloading}
	at com.brand.blockus.Instance.registerOxidizable(Instance.java:219) ~[blockus-2.7.19+1.20.1_mapped_srg_1.20.1.jar%231704!/:?] {re:classloading}
	at com.brand.blockus.Instance.addOxidizable(Instance.java:196) ~[blockus-2.7.19+1.20.1_mapped_srg_1.20.1.jar%231704!/:?] {re:classloading}
	at com.brand.blockus.Instance.init(Instance.java:182) ~[blockus-2.7.19+1.20.1_mapped_srg_1.20.1.jar%231704!/:?] {re:classloading}
	at com.brand.blockus.Blockus.onInitialize(Blockus.java:53) ~[blockus-2.7.19+1.20.1_mapped_srg_1.20.1.jar%231704!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23583!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23587!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 18 more
`
i am not totally sure what the root cause is, given that blockus has not responded to my report yet, but I thought i would mention this issue here as well just in case.

### Crash Report and latest.log

[crash-2024-10-11_18.40.06-client.txt](https://github.com/user-attachments/files/17351581/crash-2024-10-11_18.40.06-client.txt)
[latest.log](https://github.com/user-attachments/files/17351582/latest.log)
[debug.log](https://github.com/user-attachments/files/17351583/debug.log)

### Additional information

full mod list (over 460) should be in the latest.log file

**Comment by Faboslav** [comment]
Fix for this error should be out with the 3.0.4 release, its possible that in large modpacks there will be another problem, we will see :).
