### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by frikinjay** [Faboslav/friends-and-foes#37]
### Minecraft version information

1.18.2

### Mod loader information

Quilt

### Mod loader version information

0.17.0-beta2

### Mod version information

1.4.3

### Reproduction Steps

Put the mod in along with the mods i have present
Then start the client

### Crash Report and latest.log

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'friendsandfoes'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:75)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at dev.architectury.registry.level.biome.BiomeModifications.addProperties(BiomeModifications.java)
	at com.faboslav.friendsandfoes.init.ModEntity.registerBiomeModification(ModEntity.java:118)
	at com.faboslav.friendsandfoes.init.ModEntity.initBiomeModifications(ModEntity.java:82)
	at com.faboslav.friendsandfoes.init.ModEntity.init(ModEntity.java:59)
	at com.faboslav.friendsandfoes.FriendsAndFoes.initCustomRegisters(FriendsAndFoes.java:69)
	at com.faboslav.friendsandfoes.quilt.FriendsAndFoesQuilt.onInitialize(FriendsAndFoesQuilt.java:21)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58)
	... 12 more
Caused by: java.lang.ClassCastException: class dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl$$Lambda$9028/0x00000008015565e8 cannot be cast to class java.util.function.Consumer (dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl$$Lambda$9028/0x00000008015565e8 is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @56f0cc85; java.util.function.Consumer is in module java.base of loader 'bootstrap')
	at net.fabricmc.fabric.api.biome.v1.BiomeModification.add(BiomeModification.java:64)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.registerModification(BiomeModificationsImpl.java:89)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.<clinit>(BiomeModificationsImpl.java:82)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: ~~ERROR~~ LinkageError: loader constraint violation: when resolving interface method 'int com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)' the class loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @56f0cc85 of the current class, net/minecraft/class_6498, and the class loader 'app' for the method's defining class, com/sun/jna/platform/win32/Version, have different Class objects for the type com/sun/jna/ptr/IntByReference used in the signature (net.minecraft.class_6498 is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @56f0cc85, parent loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @6ad59d92; com.sun.jna.platform.win32.Version is in unnamed module of loader 'app')
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:75)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Additional information

Modlist - 
```
Loading 405 mods:
	- additionaladditions 4.0.3
	- additionalbars 3.0.0
	- adorn 3.5.0+1.18.2
	- advanced_runtime_resource_pack 0.5.7
	- advancednetherite 1.5.0-1.18.2
	- advancementplaques 1.4.4
	- advancements-enlarger 0.2.4
	- ae2 11.0.0
	- ae2things 1.1.0-beta.6
	- ae2wtlib 11.0.1
	- airaffinity 1.18.2-Fabric-v1.0.0
	- akashictomeoftools 1.2.1
	- alternate-current 1.2.1
	- amphitritecoffer 1.2.0
	- amplified-nether 1.1
	- anazm 1.0.3-universal
	- antighost 1.18.2-fabric0.47.10-1.1.4
	- appbot 1.2.1
	- appleskin 2.4.0+mc1.18.2
	- aqupdcaracal 1.18.2-1.3.8
	- aqupdgrizzly 1.18-1.3
	- architects_palette 1.7
	- architecture_extensions 0.2.0-pre5
	- architectury 4.4.68
	- archon 0.2.4
	- armor-stand-editor 1.3.2+1.18.2
	- audino 1.2.1+1.18.2_fabric
	- authme 3.1.0
	- auto_planter 18.4-fabric
	- autoconfig1u 3.4.0
	- autosmeltenchant 1.1.0
	- axolotlitemfix 1.1.3
	- badpackets 0.1.2
	- balm-fabric 3.0.0+0
	- banhammer 0.5.0+1.18.2
	- basicaiots 1.3.3+1.18.2
	- bcc fabric-1.0.5
	- bclib 1.4.7
	- bendy-lib 2.0.4
	- besmirchment 1.18.2-11
	- better_wandering_trader 1.8.0
	- better_withered_mobs 1.7.0
	- betterbeacon 1.0.8
	- betterbeds 1.2.0
	- betterdungeons 1.18.2-Fabric-2.1.0
	- bettermineshafts 1.18.2-Fabric-2.1.3
	- betterpingdisplay 1.1.1
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bewitchment 1.18-20
	- bhmenu 1.17.1-1.18.2-1.3
	- bigbeacons 1.2.5
	- blockus 2.4.7+1.18.2
	- blue_endless_jankson 1.2.1
	- bookshelf 13.0.13
	- bosses_of_mass_destruction 1.3.7-1.18.2
	- botania 1.18.2-432-FABRIC
	- brazier 4.0.3
	- breakprogress 1.0.1
	- byg 1.4
	- bygplus 2.0.1
	- can-i-mine-this-block 1.2.0
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4
	- cardinal-components-block 4.1.4
	- cardinal-components-chunk 4.1.4
	- cardinal-components-entity 4.1.4
	- cardinal-components-item 4.1.4
	- cardinal-components-level 4.1.4
	- cardinal-components-scoreboard 4.1.4
	- cardinal-components-world 4.1.4
	- carpet 1.4.69
	- carrier 1.10.0
	- cauldron_dyeing 1.0.2+1.18.2
	- chat_plus 2.1.6
	- cherishedworlds 2.0.1-1.18
	- chesttracker 1.1.16
	- chickensshed 1.18.1-1.3
	- chisel 1.4.5
	- chiselsandbits 1.2.87
	- chocolatebar 0.1.4+mc1.18.2
	- cleanview 1.18.2-v1-fabric
	- clearview 4.0.1
	- clickadv 2.6
	- clickmachine 1.2.0
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.1
	- cloth-client-events-v0 3.2.64
	- cloth-common-events-v1 3.2.64
	- cloth-config 6.2.62
	- cloth-datagen-api-v1 3.2.64
	- cloth-scissors-api-v1 3.2.64
	- cloth-utils-v1 3.2.64
	- clumps 8.0.0+8
	- cobbled_paths 0.1.7
	- columns 1.4.0
	- com_electronwill_night-config_core 3.6.4
	- com_electronwill_night-config_toml 3.6.4
	- com_eliotlash_mclib_mclib 18
	- com_eliotlash_molang_molang 18
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0
	- com_github_chocohead_fabric-asm v2.3
	- com_github_llamalad7_mixinextras 0.0.10
	- com_google_code_findbugs_jsr305 3.0.2
	- com_moandjiezana_toml_toml4j 0.7.2
	- com_neovisionaries_nv-websocket-client 2.14
	- com_typesafe_config 1.4.1
	- comforts 1.1.2-1.18.2
	- command_structures 2.0.1+1.18.2
	- computercraft 1.100.6
	- conjuring 1.0.22+1.18
	- connected-doors 1.1+1.18
	- craftingpanel 1.0.2
	- craftingtweaks 13.0.0
	- create mc1.18.2_v0.4.1+601
	- creeperoverhaul 1.3.1
	- crops_love_rain 1.2.2
	- croptopia 2.0.3
	- crowdin-translate 1.4+1.18.2
	- ctov 2.8
	- customportalapi 0.0.1-beta50-1.18
	- customstars 0.8+1.18.2
	- cyanide 2.1.0
	- dankstorage 1.18.2-3.7
	- darkpaintings 10.0.3
	- darkutils 10.0.4
	- decor4fabric 1.2
	- decorative_blocks 2.1.0
	- deepslatecutting 1.3.3
	- diggusmaximus 1.5.4-1.18
	- dimores 1.0.2
	- disable_custom_worlds_advice 2.0
	- disenchanter 0.1.6+1.18
	- display_case 1.0.0
	- dml-refabricated 1.18.2
	- dml-refabricated-base 1.18.2
	- dml-refabricated-events 1.18.2
	- dml-refabricated-modular-armor 1.18.2
	- dml-refabricated-rei 1.18.2
	- draggable-resource-packs 2.0.0
	- dripstone_fluid_lib 1.2.0
	- ducts 1.1.7
	- dynamic_asset_generator 0.6.2
	- dynamiccrosshair 1.2
	- dynamicfps 2.1.0
	- ears 1.4.5_01
	- earthtojavamobs 1.8.0+1.18.2
	- easymagic 3.3.0
	- ec-core 1.0.1-mc1.18.2
	- eldritch_mobs 1.11.0
	- ellemes_container_lib 1.4.0-beta.1
	- emerald_tools 1.3.43
	- emotecraft 2.1.3-SNAPSHOT-build.24
	- enchant_the_rainbow 1.0.1
	- enchantedbookredesign 1.17.1-2.0
	- enchdesc 10.0.3
	- enhancedblockentities 0.6+1.18.2
	- entityculling 1.5.1
	- equivalence 1.2.3
	- essential_commands 0.23.0-mc1.18.2
	- excavated_variants 0.6.2
	- expanded_armor_enchanting 1.0.2
	- expanded_axe_enchanting 1.0.3
	- expanded_trident_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- expandedstorage 7.4.0-beta.2
	- extrasponges 1.3.0
	- fabric-data-generation-api-v1 2.0.9+e19de87d60
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabricenchantments 0.7.2
	- fabricshieldlib 1.5.3-1.18
	- fabrishot ${version}
	- fake-player-api 0.3.0
	- fallingleaves 1.11.1+1.18.2
	- fancymenu 2.7.2
	- farmersdelight 1.18.2-0.2.1
	- farmingforblockheads 10.0.0
	- farsight 1.18-1.9
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2
	- figura 0.0.8+1.18.2
	- filteredreceptacles 4.0.0
	- flytre_lib 1.8.1
	- flywheel 1.18-0.7.0.26
	- forge_tags 2.1
	- forgeconfigapiport 3.2.0
	- forgottenrecipes 1.18.1-1.0.0
	- fortune-gives-experience 1.1.0
	- fractalportals 1.3.1
	- friendsandfoes 1.4.3
	- ftbchunks 1802.3.6-build.145
	- ftblibrary 1802.3.6-build.119
	- ftbteams 1802.2.6-build.51
	- fullscreeno 1.0.0
	- geckolib3 3.0.42
	- glassdoor 2.1.0+1.18
	- go-fish 1.5.0-1.18.2
	- gobber2 2.5.74
	- goblintraders 1.5.1
	- goldenhoppers 1.3.0
	- golemancy 1.2.4
	- golemsgalore 1.2.1+1.18.2
	- goodall 1.0.2
	- greater_eye 1.3.25
	- guild 0.4.0
	- haema 1.9.7+1.18.2
	- hatlist 1.2
	- health_levels 1.0.2
	- healthoverlay 6.0.1
	- here-be-no-dragons 1.0.0
	- hologram-api 0.2.1+1.18-pre5
	- holograms 1.3.1+1.18.2
	- hoverpets 0.3.3
	- hugestructureblocks 1.0.4
	- hyle 0.1.0
	- iceberg 1.0.38
	- icy-incitement 1.18.2-fabric-1.1.3
	- impersonate 2.4.1
	- incorporeal 1.18.2-2-SNAPSHOT-894c974c
	- ingredient-extension-api 2.0.5
	- inspecio 1.4.1+1.18
	- io_leangen_geantyref_geantyref 1.3.11
	- jankson 4.0.0+j1.2.0
	- java 17
	- jumpoverfences 1.16-0.0.3
	- justenoughkeys 0.5.3
	- kanos_config 0.2.0+1.14.4-1.19
	- konkrete 1.3.3
	- kronhud 2.0.3
	- ktdatataglib 1.6.5+1.18.2
	- kyrptconfig 1.4.1-1.18
	- legendarytooltips 1.2.4
	- libblockattributes 0.10.2
	- libblockattributes_core 0.10.2
	- libblockattributes_fluids 0.10.2
	- libblockattributes_items 0.10.2
	- libgui 5.3.2+1.18.2
	- libninepatch 1.1.0
	- lightoverlay 6.0.5
	- lookaround 0.10.2
	- maelstrom_library 1.2.4-1.18.2
	- malilib 0.12.1
	- maybe-data 1.3.1-1.18.2
	- megane 7.5.1
	- megane-api 7.1.0
	- megane-applied-energistics-2 7.1.0
	- megane-fabric-transfer 7.1.0
	- megane-lib-block-attributes 7.1.0
	- megane-reborn-energy 7.0.0
	- megane-runtime 7.2.0
	- megane-vanilla 7.1.1
	- midnightlib 0.3.1
	- milk 0.3.2
	- minecarttweaks 1.5
	- minecraft 1.18.2
	- mintychunk 1.18.X-1.0.3
	- mm 2.3
	- multipart_entities 1.1.5-1.18.2
	- myron 1.6.3+1.18.1
	- mysql_mysql-connector-java 8.0.28
	- naturescompass 1.18.2-2.0.3-fabric
	- netherportalfix 9.0.0
	- no_angled_brackets 1.0.0
	- no_null_processors 2.0.1+1.18.1
	- noindium 1.0.1+1.18.2
	- noooooo 1.0.0
	- omega-config 1.2.3-1.18.1
	- openloader 12.0.1
	- org_aperlambda_lambdajcommon 1.8.1
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2
	- org_luaj_luaj-jse 3.0.1
	- org_spongepowered_configurate-core 4.1.2
	- org_spongepowered_configurate-hocon 4.1.2
	- org_xerial_sqlite-jdbc 3.36.0.3
	- orientation 2.1.0
	- owo 0.7.2+1.18
	- packet_tweaker 0.3.0+1.18.2
	- patchouli 1.18.2-67-FABRIC
	- pehkui 3.2.2+1.14.4-1.19
	- placeholder-api 1.1.3+1.17.1
	- playerabilitylib 1.5.0
	- polymer 0.2.0-rc.2+1.18.2
	- polymer-legacy 0.1.9+0.2.0-rc.2+1.18.2
	- polymorph 0.0.21-1.18.2
	- porting_lib 1.1.310-beta+1.18.2-dev.ba26474
	- pugh_lib 1.3.0
	- pugh_tools 1.2.5
	- puzzleslib 3.3.5
	- quarryplus 18.4.569
	- quilt_base 1.1.0-beta.18+1.18.2
	- quilt_biome 1.1.0-beta.18+1.18.2
	- quilt_block_extensions 1.1.0-beta.18+1.18.2
	- quilt_client_command 1.1.0-beta.18+1.18.2
	- quilt_command 1.1.0-beta.18+1.18.2
	- quilt_crash_info 1.1.0-beta.18+1.18.2
	- quilt_dimension 1.1.0-beta.18+1.18.2
	- quilt_item_group 1.1.0-beta.18+1.18.2
	- quilt_item_setting 1.1.0-beta.18+1.18.2
	- quilt_lifecycle_events 1.1.0-beta.18+1.18.2
	- quilt_loader 0.17.0-beta.2
	- quilt_networking 1.1.0-beta.18+1.18.2
	- quilt_recipe 1.1.0-beta.18+1.18.2
	- quilt_registry 1.1.0-beta.18+1.18.2
	- quilt_registry_entry_attachments 1.1.0-beta.18+1.18.2
	- quilt_resource_loader 1.1.0-beta.18+1.18.2
	- quilt_screen 1.1.0-beta.18+1.18.2
	- quilt_tags 1.1.0-beta.18+1.18.2
	- quilt_tooltip 1.1.0-beta.18+1.18.2
	- quilted_fabric_api 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_api_base 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_api_lookup_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_biome_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_blockrenderlayer_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_command_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_commands_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_containers_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_content_registries_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_convention_tags_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_crash_report_info_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_dimensions_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_entity_events_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_events_interaction_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_events_lifecycle_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_game_rule_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_item_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_item_groups_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_key_binding_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_keybindings_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_lifecycle_events_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_loot_api_v2 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_loot_tables_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_mining_level_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_models_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_networking_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_networking_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_object_builder_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_particles_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_registry_sync_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_renderer_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_renderer_indigo 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_renderer_registries_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_rendering_data_attachment_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_rendering_fluids_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_rendering_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_rendering_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_resource_conditions_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_resource_loader_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_screen_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_screen_handler_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_textures_v0 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_transfer_api_v1 1.0.0-beta.19+0.55.1-1.18.2
	- quilted_fabric_transitive_access_wideners_v1 1.0.0-beta.19+0.55.1-1.18.2
	- reach-entity-attributes 2.1.1
	- registrate-fabric MC1.18.2-1.0.3
	- rhino 1802.1.13-build.175
	- roughlyenoughitems 8.2.471
	- roughlyenoughresources 2.5.0
	- roughlysearchable 2.4.1+1.18.2
	- rpgdifficulty 1.0.12
	- satin 1.7.2
	- serialization_hooks 0.2.0+1.18.cb29164
	- server_translations_api 1.4.12+1.18.2
	- sgui 1.0.2+1.18.2
	- shetiphiancore 1.2.10
	- shwfox 1.3+fabric
	- sihywtcamd 1.6+1.18
	- smoothboot 1.18.2-1.7.0
	- smoothchunk 1.18.2-1.9
	- someforgepatchesported 1.0.3
	- spruceui 3.3.0+1.17
	- step-height-entity-attribute 1.0.0
	- team_reborn_energy 2.0.0-beta1
	- terrablender 1.1.0.101
	- terraform-wood-api-v1 3.0.0
	- thonkutil 2.14.1+1.18
	- thonkutil-base 1.12.2+23c1dc2c60
	- thonkutil-capes-v1 1.3.2+9e23427060
	- thonkutil-coords-v1 1.0.19+9b80223760
	- thonkutil-customization-v1 1.0.14+9b80223760
	- thonkutil-legacy 1.0.20+9b80223760
	- thonkutil-modchecker-v1 1.0.12+9b80223760
	- thonkutil-potions-v0 1.4.1+9b80223760
	- thonkutil-titlescreen-v1 1.1.9+9b80223760
	- thonkutil-trades-v1 1.1.20+9b80223760
	- trinkets 3.3.1
	- tweakeroo 0.13.3
	- universal-graves 2.0.3+1.18.2
	- uteamcore 4.0.0.2
	- wands 2.5_mc1.18.2
	- whereisit 1.14.10
	- wthit 4.10.3
	- xlpackets 2.1-1.17.1
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0
```

**Comment by Faboslav** [comment]
Hello, right off my head, last loader version i tested quilt on was was 0.16, also it is possible that this is related to architectury not my mod. I will look at this after i am done releasing 1.19 versions.

**Comment by Faboslav** [comment]
I am sorry for the delay, i will do some testing today (with the fixes i did) and probably release working version.
