### ISSUE TITLE
Crash in Local Multiplayer

### ISSUE THREAD

**Issue by Muffintiem** [Faboslav/friends-and-foes#6]
### Minecraft version information

1.18

### Mod version information

1.0.1

### Reproduction Steps

1. Have someone start a single player game with this mod included.
2. Have them open to LAN.
3. If a second player tries to connect locally they get booted immediately.

### Crash Report and latest.log

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/3/21, 4:59 PM
Description: Getting block state

net.minecraft.class_6558: Missing Palette entry for index 0.
	at net.minecraft.class_2814.method_12288(class_2814.java:64)
	at net.minecraft.class_2841.method_12331(class_2841.java:147)
	at net.minecraft.class_2841.method_12321(class_2841.java:141)
	at net.minecraft.class_2826.method_12254(class_2826.java:50)
	at net.minecraft.class_2818.method_8320(class_2818.java:181)
	at net.minecraft.class_1937.method_8320(class_1937.java:401)
	at net.minecraft.class_1297.method_23312(class_1297.java:804)
	at net.minecraft.class_1297.method_25936(class_1297.java:1284)
	at net.minecraft.class_1309.method_32325(class_1309.java:524)
	at net.minecraft.class_1309.method_6007(class_1309.java:2660)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_1420.method_5773(class_1420.java:128)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2814.method_12288(class_2814.java:64)
	at net.minecraft.class_2841.method_12331(class_2841.java:147)
	at net.minecraft.class_2841.method_12321(class_2841.java:141)
	at net.minecraft.class_2826.method_12254(class_2826.java:50)
	at net.minecraft.class_2818.method_8320(class_2818.java:181)
	at net.minecraft.class_1937.method_8320(class_1937.java:401)
	at net.minecraft.class_1297.method_23312(class_1297.java:804)
	at net.minecraft.class_1297.method_25936(class_1297.java:1284)
	at net.minecraft.class_1309.method_32325(class_1309.java:524)
	at net.minecraft.class_1309.method_6007(class_1309.java:2660)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_1420.method_5773(class_1420.java:128)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)

-- Block being got --
Details:
	Location: World: (-1281,-19,-89), Section: (at 15,13,7 in -81,-2,-6; chunk contains blocks -1296,-64,-96 to -1281,319,-81), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,-64,-512 to -1025,319,-1)
Stacktrace:
	at net.minecraft.class_2818.method_8320(class_2818.java:181)
	at net.minecraft.class_1937.method_8320(class_1937.java:401)
	at net.minecraft.class_1297.method_23312(class_1297.java:804)
	at net.minecraft.class_1297.method_25936(class_1297.java:1284)
	at net.minecraft.class_1309.method_32325(class_1309.java:524)
	at net.minecraft.class_1309.method_6007(class_1309.java:2660)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_1420.method_5773(class_1420.java:128)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Entity being ticked --
Details:
	Entity Type: minecraft:bat (net.minecraft.class_1420)
	Entity ID: 3119
	Entity Name: Bat
	Entity's Exact location: -1280.69, -18.30, -88.19
	Entity's Block location: World: (-1281,-19,-89), Section: (at 15,13,7 in -81,-2,-6; chunk contains blocks -1296,-64,-96 to -1281,319,-81), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,-64,-512 to -1025,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['muffintiem'/3115, l='ClientLevel', x=-1229.13, y=74.00, z=-142.43]]
	Chunk stats: 5041, 2182
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 391155 game time, 612530 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, HMLM.zip, BetterAzaleasv2.zip, s33r-rainbow-amethyst.zip, 3D+Mushrooms+v1.1.zip, MuddySlime.zip, Better+Dripstone+3D+[1.17+].zip, squirrelfix.zip

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1497169944 bytes (1427 MiB) / 2373976064 bytes (2264 MiB) up to 5033164800 bytes (4800 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a52
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9365
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25162.75
	Virtual memory used (MB): 11194.39
	Swap memory total (MB): 9011.28
	Swap memory used (MB): 629.13
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4800m
	Fabric Mods: 
		allarrowsinfinityfix: All Arrows Infinity Fix 1.0.0
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		aqupdcaracal: Caracal mob 1.18-1.3.3
		architectury: Architectury 3.0.39
		autofish: Autofish 0.9.3
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		beehivetooltips: Beehive Tooltips 1.4.0-b1
		bettersafebed: BetterSafeBed 1.18-fabric-a
		betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.5
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		citresewn: CITResewn 0.8.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.42
		cloth-config-lite: cloth-config-lite 2.0.6
		coldsnaphorde: Cold Snap Horde 1.0.2-1.18
		collective-fabric: Collective (Fabric) 3.9
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		cosmetic-armor: Cosmetic Armor 1.2.0
		croptopia: Croptopia 1.7.0
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		earthtojavamobs: Earth2Java 1.7.4+1.18
		elementalcreepers: Elemental Creepers: Refabricated 1.4.0+1.18-pre5
		enhancedcelestials: Enhanced Celestials 2.0.6
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		extractpoison-fabric: Extract Poison (Fabric) 1.6
		fabric: Fabric API 0.43.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.5+3ac43d9514
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+3ac43d9514
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9514
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9514
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd14
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c614
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d14
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9514
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957114
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.15+3ac43d9514
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.5+b4f4f6cd14
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9514
		fabric-item-api-v1: Fabric Item API (v1) 1.2.7+3ac43d9514
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f314
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd14
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9514
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd14
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9514
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd14
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.13+3ac43d9514
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.7+3ac43d9514
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac14
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d9514
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9514
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9514
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd14
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.3+d154e2c614
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9514
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd14
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a14
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9514
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9514
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a714
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9514
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+b4f4f6cd14
		fabricloader: Fabric Loader 0.12.8
		fiber: fiber 0.23.0-2
		friendsandfoes: Friends&Foes 1.0.1
		geckolib3: Geckolib 3.0.20
		geodes: More Geodes 1.2.0
		glow: Actually Glow Berries 1.0.2
		go-fish: Go Fish 1.4.0-1.18
		gobber2: Gobber2 2.5.50
		greater_eye: Greater Eye of Ender 1.3.15
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		handoveryouritems-fabric: Hand Over Your Items (Fabric) 1.3
		hookshot: Hookshot 23.0
		illuminations: Illuminations 1.10.2
		incapacitated: Incapacitated 1.1-1.18
		inventorytotem-fabric: Inventory Totem (Fabric) 1.5
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lowfire: Low Fire 1.17-2.0.0
		malilib: MaLiLib 0.10.0-dev.24
		mavm: More Axolotl Variants Mod 1.0.5
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		modmenu: Mod Menu 3.0.0
		mooshroomtweaks-fabric: Mooshroom Tweaks (Fabric) 1.6
		more_gems: More Gems 1.3.49
		musicdr: Music Duration Reducer 1.2.1
		mythic-mounts: Mythic Mounts 4.0
		netherportalspread-fabric: Nether Portal Spread (Fabric) 5.6
		onsoulfire: On Soul Fire 1.18-1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		petnames-fabric: Pet Names (Fabric) 1.6
		petowner: Pet Owner 1.8.2-1.18-pre4+
		pugh_lib: Pugh Lib 1.2.11
		pugh_tools: Pugh Tools 1.1.13
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.0.339
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 1.9
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 1.5
		spidersproducewebs-fabric: Spiders Produce Webs (Fabric) 1.5
		squirrels: Squirrels 1.2.1-1.18
		stacc: Stacc 1.3.0
		stacker: Stacker 2.0.0
		statuseffecttimer: Status Effect Timer 1.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		trinkets: Trinkets 3.1.0
		villagerdeathmessages-fabric: Villager Death Messages (Fabric) 2.2
		windchimes: Windchimes 1.2.0
		wmitaf: WMITAF mc1.18-pre5-2.1.3
		wthit: wthit 4.2.0
		xaerominimap: Xaero's Minimap 21.22.3
		xaeroworldmap: Xaero's World Map 1.18.4
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(R) Plus Graphics GL version 3.2.0 - Build 27.20.100.9365, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/HMLM.zip, file/BetterAzaleasv2.zip, file/s33r-rainbow-amethyst.zip, file/3D+Mushrooms+v1.1.zip, file/MuddySlime.zip, file/Better+Dripstone+3D+[1.17+].zip, file/squirrelfix.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

### Additional information

Both of us were able to use this mod fine in single player and we were able to play together fine once we both removed the mod. I just hope this will be fixed soon so we can put it back in.

**Comment by Faboslav** [comment]
I can confirm that this is happening. 

Thank you for your time, hopefully i will be able to fix this today.

**Comment by Faboslav** [comment]
@Muffintiem
I fixed all related issues and tested them on LAN server, localhost dedicated server and remote dedicated server.

Can you please download the 1.0.2 version and confirm that it is working? You can download it here:
- https://www.curseforge.com/minecraft/mc-mods/friends-and-foes/files/3548938
- https://modrinth.com/mod/friends-and-foes/version/oH9S375Y
- https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.18-1.0.2

**Comment by Muffintiem** [comment]
That fixed it.

**Comment by Faboslav** [comment]
Great! I hope you will have a great time playing with this mod.
