### ISSUE TITLE
Friends and Foes preventing me from joining my server

### ISSUE THREAD

**Issue by Eatham532** [Faboslav/friends-and-foes#75]
### Minecraft version information

1.19.2

### Mod loader information

Fabric

### Mod loader version information

0.14.9

### Mod version information

1.5.12

### Reproduction Steps

It is really difficult to explain how to reproduce this bug. I have a bunch of mods on my server. When I join, I crash. I use not enough crashes and it says that the crash is to do with Friends and Foes. 

### Crash Report and latest.log

https://crashy.net/d58YQ64zlEfHtX9KGcb2
[latest.log](https://github.com/Faboslav/friends-and-foes/files/9958741/latest.log)

**Comment by Faboslav** [comment]
Is there any context on the location, is there any modded structure? Do you use some compat pack for Friends&Foes for example with Repurposed structures?

**Comment by Faboslav** [comment]
Also was this working with 1.5.11, or is this the first version with the problem?

**Comment by Eatham532** [comment]
I don't know. Will have to check tomorrow.

**Comment by Faboslav** [comment]
I tried to test in-game following cases in a new world:
- All four copper golem related village structures (in each village type one structure)
- Spawn of copper golem by command
- Spawn of different copper golems by building blocks

No crash yet, i am not sure how to approach this, i mean i can fix this with a hacky solution, but it would be much better for the future of the mod if we can determine certain reproduction steps. Even if that means, that you will provide me your server setup(mods, world etc) (that would be probably perfect) if we dont come up with anything else.

**Comment by Eatham532** [comment]
It also does not work with 1.5.11.

Here is the server log when I joined.

```
User Authenticator #1/INFO06:51:38
UUID of player Eatham532 is 43d24325-0ac2-454b-a708-62ebd28559de
Server thread/INFO06:51:38
[Handshake]: Sending channel query
Sent link to Eatham532
Netty Epoll Login IO Thread #0/INFO06:51:38
[Handshake]: Receiving client channels
[Handshake]: Handshake completed successfully
Server thread/INFO06:51:41
Eatham532[/192.168.0.1:55832]: logged in with entity id 133 at (-36.14054448064617, 67.0, -40.69999998807907)
Using Fabric Permissions API
06:51:42
multiplayer.player.joined
Async chunk loading for player Eatham532 completed
Netty Epoll Play IO Thread #0/INFO06:51:42
[STDOUT]: VMP: Started priority handler
Console06:51:45
at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$bcc000$modifiedRunLoop(MinecraftServer.java:4394) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Server thread/ERROR06:51:45
Invalid polymer:sync/request (-1) packet received from client Eatham532 (43d24325-0ac2-454b-a708-62ebd28559de)! {}
Console06:51:45
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1/24)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.77.Final.jar:?]
at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.77.Final.jar:?]
at net.minecraft.class_2540.readByte(class_2540.java:1192) ~[server-intermediary.jar:?]
at net.minecraft.class_2540.method_10816(class_2540.java:441) ~[server-intermediary.jar:?]
at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.handle(PolymerServerProtocolHandler.java:40) ~[polymer-0.2.17+1.19.2-a17e1a1b55f8056e.jar:?]
at net.minecraft.class_3244.handler$fmd000$polymer_catchPackets(class_3244.java:13187) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_12075(class_3244.java) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[server-intermediary.jar:?]
at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[server-intermediary.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$bcc000$modifiedRunLoop(MinecraftServer.java:4394) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Server thread/INFO06:51:45
[bclib]: Received Hello from Client. (server=2.1.2, client=2.1.2)
[bclib]: Sending Hello to Client. (server=2.1.2)
Server thread/ERROR06:51:45
[worlds_together]: Unable to parse Version in jar:file:///home/amp/.ampdata/instances/PeopleSmp01/Minecraft/mods/xercapaint-fabric-1.19.2-1.0.0.jar
Server thread/INFO06:51:46
[bclib]: - Listing Mod bclib v2.1.2 (size: 1812.3 KiB, download=true)
[bclib]: - Offering Config bclib.CONFIG_bclib.generator
[bclib]: - Offering Config bclib.CONFIG_bclib.main
[bclib]: - Offering Config bclib.CONFIG_bclib.recipes
[bclib]: - Offering Config bclib.CONFIG_bclib.biomes
[bclib]: - Offering Folder /home/amp/.ampdata/instances/PeopleSmp01/Minecraft/bclib-sync (allowDelete=true)
Received secret request of Eatham532 (15)
Sent secret to Eatham532
06:51:50
Mean tick: 52ms decreasing chunk view distance to: 9
Changing watch distance to 10
Changing watch distance to 10
Changing watch distance to 10
Changing watch distance to 10
Server thread/WARN06:51:50
Can't keep up! Is the server overloaded? Running 8415ms or 168 ticks behind
Server thread/INFO06:51:52
Player Eatham532 joined with a matching carpet client
VoiceChatPacketProcessingThread/INFO06:51:53
Successfully authenticated player 43d24325-0ac2-454b-a708-62ebd28559de
Server thread/INFO06:51:54
Eatham532 lost connection: multiplayer.disconnect.generic
multiplayer.player.left
Disconnecting client Eatham532
```

**Comment by Eatham532** [comment]
Also did some checks to see if it works without VMP. That is not the issue. The only main overworld mod that I use to change the generation is Traverse. But the twilight forest may do something as well.

**Comment by Eatham532** [comment]
Maybe it is bclib. These are better end blocks :P
![2022-11-09_07 47 41](https://user-images.githubusercontent.com/78714349/200672172-fff242f9-0b0d-40a6-b269-e284aef7c81b.png)

**Comment by Eatham532** [comment]
I fixed it, :) Bclib had weird configs. There was no better end on the server and yeh. Weird stuff.

**Comment by Faboslav** [comment]
@Eatham532 What was the issue then, i dont get it, how bclib can cause crash in friends&foes code?

**Comment by Eatham532** [comment]
My world was a bit corruped
