### ISSUE TITLE
Crash with Debugify Reforged

### ISSUE THREAD

**Issue by chadzar** [Faboslav/friends-and-foes#82]
### Minecraft version information

1.19.2

### Mod loader information

Forge

### Mod loader version information

43.2.1 (Forge)

### Mod version information

1.6.3

### Reproduction Steps

1. Put Debugify Reforged and Friends&Foes with the dependencies (Cloth Config/Architectury API)
2. Launch the game

### Crash Report and latest.log

 java.lang.reflect.InvocationTargetException 	
               at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	
               at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	
               at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	
               at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	
               at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 	
               at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 	
               at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 	
               at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
 Caused by: java.lang.reflect.InvocationTargetException 	
               at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	
               at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	
               at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	
               at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	
               at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) 	
               ... 9 more 
Caused by: java.lang.module.ResolutionException: Module debugify contains package com.llamalad7.mixinextras, module MixinExtras exports package com.llamalad7.mixinextras to debugify 	
               at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901) 	
               at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807) 	
               at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736) 	
               at java.base/java.lang.module.Resolver.finish(Resolver.java:380) 	
               at java.base/java.lang.module.Configuration.<init>(Configuration.java:140) 	
               at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494) 	
               at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75) 	
               at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60) 	
               at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104) 	
               at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77) 	
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) 	
               at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) 	
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) 	... 14 more 
Dec 20, 2022 3:42:51 PM org.prismlauncher.EntryPoint main 
INFO: Exiting with 1 
Process exited with code 1.

**Comment by Faboslav** [comment]
I already fixed issue with the fabric debugify on my side, there is nothing more i can do.

**Comment by Faboslav** [comment]
Also it is unofficial port and it seems abandoned. I would recommend to stop using mods like that.

**Comment by chadzar** [comment]
ok, I will move to fabric
